config/routes.rb
=begin
Main file for listing out different urls/paths a customer can go to.
Points to file in folders to the left. pages#about -> pages/about.html.erb
=end

Rails.application.routes.draw do
  devise_for :users
 root to: 'pages#home'
 get 'about', to: 'pages#about'
 resources :contacts, only: :create
  # ^This auto generated many lines when you check 'rails routes' in terminal.
  # including /new_contact, edit_contact, and many more.  
 get 'contact-us', to: 'contacts#new', as: 'new_contact'
   # ^Changes URL from contacts/new to contact-us
 get 'my-hubspot', to: 'pages#myhubspot'
 end

# Get requests are the most common requests, sent anytime you go to x.com 
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
=begin
Controller file made w/ home.html.erb and routes.rb that work together to make the homepage
Thus, The file name (home, about, etc.) must match the method name from the controllers file

It works something like this:
    1. Someone hits home page -> 
    2. routes.rb file reads root pointing to pages controller and home method (pages#home) -> 
    3. rails checks controller file (pages_controller) and see home action -> 
    4. rails gathers corresponding view file -> 
    5. sends all this back to user 

The class 'pagescontroller' come from the rails backend

Not sure why I have an entry for home and about but not contact us. 
=end


class PagesController < ApplicationController
    # Get request for / which is our home page
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
end

    def about
    end
    
    def myhubspot
    end

app/helpers/application_helper.rb
=begin
    http://www.rubydoc.info/github/shareaprayer/shareaprayer/ApplicationHelper
    Helpers found in the ApplicationHelper are present in all views on the site.
=end

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!--When you add code to layout it'll show up on every page.
Adding code will show up everywhere. Good for stuff like a navbar.
-->

<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
      <i class=" fa fa-university"></i>
      Westeros
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
            <!-- Could have had "/users/login" instead of new_user_session but 
            best practice is to include path name from either routes.rb or using 
            the rails routes command to find the 'prefix'-->
          <% end %>
        </div>
      <ul class="nav navbar-nav navbar-right">
        <!-- Could write this w/ raw html using <a href='/about_us" class="x">About Us</a>
        but below is best practice on how to add rails links --> 
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
        <li><%= link_to "My HubSpot", my_hubspot_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
      <div class="container">
        <% flash.each do |type, msg| %>
         <!-- shows messages from contacts_controller -->
          <%= content_tag :div, msg, class: "alert alert-#{type}" %>
          <!--Used rails to create div for us.
          Using string interpulation. Type refers to key we use, danger or success
          msg assigns to whatever assigned to keys in hash (like "Message sent")
        <% end %>
        <!-- Moved flash.each loop from new.html.erb to here so users won't only see flash messages
        when on the contact form --> 
        </div>
      <%= yield %>
  </body>
</html>

app/views/pages/myhubspot.html.erb
<div class ="container-fluid text-center">
    <div class="row">
        <div class="col-md-12">
            <h1>Contacts</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <table class="table table-striped table-bordered">
                <thead class="thead">
                    <tr>
                        <th scope="col" >First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Company</th>
                        <th scope="col">Email</th>
                        <th scope="col">City</th>
                    </tr>
                </thead>    
                <tbody>      
                    <% 
                        ( Hubspot::Contact.all({ property: ['email', 'lastname', 'company', 'firstname', 'city'] }) ).each do |contact|
                        info = contact.properties
                    %>
                        <tr>
                            <th scope="row"><%= info[:firstname] %></th>
                            <th scope="row"><%= info[:lastname] %></th>
                            <th scope="row"><%= info[:company] %></th>
                            <th scope="row"><%= info[:email] %></th>
                            <th scope="row"><%= info[:city] %></th>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>